name: Generate Snake
on:
  schedule: 
    - cron: "0 0 * * *" # Runs at midnight UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Generate Contribution Snake
        uses: Platane/snk@v2
        with:
          github_user_name: Amila619 # Replace with your GitHub username
          output: dist/snake.svg
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
